# Generated by Django 3.2.13 on 2022-06-01 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendence',
            options={'verbose_name': 'attendence', 'verbose_name_plural': 'attendence'},
        ),
        migrations.AlterModelOptions(
            name='student_realtions',
            options={'verbose_name': 'student_realtions', 'verbose_name_plural': 'student_realtions'},
        ),
        migrations.AlterModelOptions(
            name='subject',
            options={'verbose_name': 'subject', 'verbose_name_plural': 'subjects'},
        ),
        migrations.AlterModelOptions(
            name='teacher_relations',
            options={'verbose_name': 'teacher_relation', 'verbose_name_plural': 'teacher_relations'},
        ),
        migrations.AlterModelOptions(
            name='user_model',
            options={'verbose_name': ('user_model',), 'verbose_name_plural': 'user_models'},
        ),
        migrations.AlterField(
            model_name='user_model',
            name='email',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='user_model',
            name='password',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
